(function(){
  'use strict';
  const D=window.ARCADE_COURSE,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const KEY='arcade-outline-v3',read=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}');}catch{return {};}};
  const saved=read(KEY),previous=read('arcade-beginner-v2'),old=read('arcade-course-v1');let current=0,step=0,returnFocus=null,scan=saved.scan??previous.scan??old.scanlines??false,reduced=saved.reduced??previous.reduced??old.reduced??matchMedia('(prefers-reduced-motion: reduce)').matches;
  let visited=new Set(Array.isArray(saved.visited)?saved.visited:[]),checks=Array.isArray(saved.checks)?saved.checks:Array.isArray(previous.checks)?previous.checks:[],practiceNote=saved.practiceNote??previous.practiceNote??'';
  const hash=decodeURIComponent(location.hash.slice(1)).split('/'),found=D.chapters.findIndex(c=>c.id===hash[0]);
  if(found>=0){current=found;step=Math.min(Math.max(0,(Number(hash[1])||1)-1),D.chapters[current].steps.length-1);}else if(saved.chapter&&D.chapters.some(c=>c.id===saved.chapter)){current=D.chapters.findIndex(c=>c.id===saved.chapter);step=Math.min(saved.step||0,D.chapters[current].steps.length-1);}
  const builds={v1:{name:'第一版',label:'30 秒 / 没有危险',stage:1},v2:{name:'修改版',label:'45 秒 / 只改时长',stage:2},v3:{name:'危险版',label:'45 秒 / 捡到即得分',stage:3},v4:{name:'创意版',label:'45 秒 / 带回才算',stage:4},fault:{name:'教学故障样本',label:'故意错误：一块 +20',stage:2}};
  const buildPath=id=>`practice/${id}/index.html`;
  function save(){try{localStorage.setItem(KEY,JSON.stringify({chapter:D.chapters[current].id,step,visited:[...visited],scan,reduced,checks,practiceNote}));}catch{}}
  function chip(t,c=''){return `<span class="tag ${c}">${esc(t)}</span>`;}
  function frame(title,body,caption='操作示意 · 非真实应用截图'){return `<section class="instruction-board"><div class="board-bar"><span class="window-dots" aria-hidden="true">■ ■ ■</span><b>${esc(title)}</b><span class="board-badge">${esc(caption)}</span></div><div class="board-inner">${body}</div></section>`;}
  function game(id){const b=builds[id];return frame(`BUILD ${id.toUpperCase()} · ${b.name}`,`<div class="preview-hud"><span>TIME <b>${b.stage===1?'30':'45'}</b></span><span>SCORE <b>000</b></span>${b.stage===4?'<span>BAG <b>000</b></span>':''}${chip(b.label,id==='fault'?'red':'gold')}</div><div class="game-preview"><canvas width="960" height="540" data-preview="${id}" aria-label="${esc(b.name)}初始游戏画面"></canvas><button class="play-overlay" data-play="${id}" aria-label="试玩${esc(b.name)}">▶<span>点击试玩</span></button></div><div class="build-actions"><button class="primary" data-play="${id}">▶ 试玩${esc(b.name)}</button><a class="secondary" href="${buildPath(id)}" target="_blank" rel="noopener">单独打开 ↗</a><a class="text-link" href="${buildPath(id)}" download="index.html">下载此版</a></div>`,id==='fault'?'故意制作的故障样本':'实际游戏初始画面 · 预制教学版本');}
  function flow(items){return `<div class="operation-flow">${items.map((x,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><b>${esc(x[0])}</b><p>${esc(x[1])}</p></div>`).join('')}</div>`;}
  function folder(scene){let title='桌面 › 我的矿工',rows='',caption='在空文件夹里开始，不需要预先写代码。';
    if(scene==='empty')rows='<div class="empty-folder"><span class="folder-pixel">▰</span><h2>此文件夹为空</h2><p>游戏文件之后会出现在这里。</p></div>';
    else if(scene==='backup'){title='桌面';rows='<div class="file-row"><span>▰</span><div><b>我的矿工</b><small>Codex 继续修改这里</small></div><em>当前项目</em></div><div class="copy-arrow">复制 → 粘贴 → 重命名</div><div class="file-row"><span>▰</span><div><b>我的矿工_30秒备份</b><small>刚才能玩的版本，暂时不改它</small></div><em>备份</em></div>';caption='两个文件夹并排放；不要用剪切，也别把备份放在原项目内部。';}
    else {if(scene==='unzip')title='解压后的新位置 › 我的矿工_交付版';if(scene==='deliver')title='桌面 › 我的矿工_交付版';rows='<div class="file-head"><span>名称</span><span>类型</span></div><div class="file-row selected"><span class="html-file">&lt;/&gt;</span><div><b>index.html</b><small>双击这个文件，浏览器打开游戏</small></div><em>HTML 文档</em></div><div class="file-callout"><span>↑</span>不是聊天截图，也不是 index.html.txt</div>';caption=scene==='unzip'?'核对地址栏：现在打开的是解压后的副本，不是原开发文件夹。':'本课下载版的规则、图形和代码都放在同一个 HTML 文件内。';}
    return frame('找到你的游戏文件',`<div class="explorer-address">←　↑　 <span>▰　${esc(title)}</span></div><div class="explorer-content">${rows}</div><p class="diagram-caption">${esc(caption)}</p>`);
  }
  function visual(s){switch(s.visual){
    case 'game':case 'bug':return game(s.build);
    case 'agent':return frame('AI AGENT / 它能执行哪些事情',`<div class="agent-lead"><span class="agent-face">AI</span><div><h2>不只回答，还能用工具做事。</h2><p>前提：你选对文件夹，并允许相应操作。</p></div></div><div class="agent-jobs">${[['读','看项目文件','找游戏入口，理解现有规则'],['写','创建 / 修改文件','把计时、移动、计分写进游戏'],['查','调用工具检查','检查代码，尝试运行并记录问题'],['改','按反馈继续修','根据你的操作与截图定位问题']].map(x=>`<div><i>${x[0]}</i><b>${x[1]}</b><p>${x[2]}</p></div>`).join('')}</div><div class="human-job"><b>你来做</b><span>说清玩法 → 看权限 → 实际试玩 → 决定改什么</span></div>`,'能力说明 · 不代表本页正在调用 AI');
    case 'setup':return s.scene==='install'?frame('准备工具 / Windows',flow([['安装','官方页面 → Windows 桌面端'],['登录','使用公司批准或本人获准账号'],['选择 Codex','新桌面端：产品下拉菜单 → Codex']])+`<div class="environment-split"><div><b>课堂看演示</b><p>本课网页 + 预制文件<br>不需要登录，不实时生成</p></div><div><b>课后自己制作</b><p>桌面端 + 可用账号 + 网络<br>AI 才能接收任务、创建文件</p></div></div>`):frame('把练习文件夹交给 Codex',`<div class="project-map"><div class="map-folder">▰<strong>我的矿工</strong><small>你创建的空文件夹</small></div><div class="map-arrow">关联 →</div><div class="map-project"><b>本地项目</b><p>项目 / Projects</p><p>编辑项目 → 添加文件夹</p><span class="path-check">检查路径指向「我的矿工」</span></div></div><div class="command-sample">先问：<br>“请告诉我当前工作的完整文件夹路径。”</div><p class="diagram-caption">若你的安装版本按钮不同，按官方说明找本地项目/文件夹入口；先确认路径，再让它写文件。</p>`);
    case 'permission':return frame('只把练习目录交给它',`<div class="permission-cards"><div><h2>这次需要</h2><p>✓ 读取练习文件夹</p><p>✓ 创建、修改 index.html</p><p>✓ 对游戏做必要检查</p></div><div><h2>这次不需要</h2><p>× 删除已有项目</p><p>× 读取无关账号和密钥</p><p>× 上传文件、安装额外软件</p></div></div><p class="diagram-caption">有确认弹窗时看清“做什么、在哪做”。不确定先问，不要习惯性全部允许。</p>`,'权限边界示意 · 不模拟授权弹窗');
    case 'folder':return folder(s.scene);
    case 'prompt':return frame('第一条消息 / 直接给 AI',`<div class="prompt-paper">${D.prompts.first.split('\n').map((p,i)=>`<div><span>${['文件','规则','范围','交付'][i]}</span><p>${esc(p)}</p></div>`).join('')}</div><button class="primary" data-copy="first">复制这条消息</button>`,'你要发送的内容 · 非 AI 回复');
    case 'response':return frame('发送后，按实际状态继续',`<div class="response-list">${[['AI 在问你','它需要你确定玩法或取舍','按第一版范围回答，不顺手增加功能。'],['AI 只给了方案','还不等于创建游戏','发“请直接创建文件”，确认进入执行。'],['AI 完成了修改','开始找文件和检查','看路径、已检查项、未检查项，再打开游戏。']].map((x,i)=>`<div><span>${i+1}</span><section><h2>${x[0]}</h2><p>${x[1]}</p><b>${x[2]}</b></section></div>`).join('')}</div>`,'阅读方法 · 不是伪造的聊天记录');
    case 'diff':return frame('把想改的地方说成一句明确要求',`<div class="time-change"><div><span>修改前</span><strong>30<small>秒</small></strong></div><i>→</i><div><span>修改后</span><strong>45<small>秒</small></strong></div></div><div class="keep-grid">${['每块 10 分','相同矿石位置','相同移动速度','没有敌人'].map(x=>`<span>✓ ${x}</span>`).join('')}</div><div class="command-sample">“只改每局时长，其他保持不变。”</div><p class="diagram-caption">发给 AI 后，还要重新打开、刷新，并开始新一局检查。</p>`,'教学修改要求 · 两份真实文件可对照');
    case 'compare-time':return frame('不是看回复，是打开两份游戏',`<div class="compare-cards"><div><span class="pixel-number">30s</span><h2>第一版</h2><p>移动、捡矿、计分</p><button data-play="v1" class="secondary">试玩 30 秒版</button></div><div><span class="pixel-number gold">45s</span><h2>第一次修改</h2><p>只改时长，其他不变</p><button data-play="v2" class="primary">试玩 45 秒版</button></div></div><div class="check-strip">按开始看时间 → 捡矿看分数 → 等结束 → 再重开</div>`,'预制文件对照 · 不实时生成');
    case 'bug-report':return frame('一条 AI 能继续处理的问题',`<div class="fault-link"><span>先实际捡一块，再描述现象</span><button class="secondary" data-play="fault">▶ 教学故障样本</button></div><div class="bug-observation"><span>只捡一块</span><b>0 → <em>20</em></b><span>但要求是 +10</span></div><div class="report-lines">${[['操作','点开始 → 捡左上第一块'],['实际','0 分变成 20 分，矿石消失'],['预期','只加 10 分，不能重复拾取'],['范围','只修计分，不改时间与地图']].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div>`,'教学故障：故意将每块分值写错');
    case 'rules':return frame('把“多拿一块？”变成可实现的规则',`<div class="rule-route"><div><span>◆</span><b>捡矿</b><p>背包 +10<br>已入账不变</p></div><i>→</i><div><span>⌂</span><b>回基地</b><p>背包转入账<br>背包归零</p></div><i>／</i><div><span>!</span><b>碰到怪</b><p>丢掉背包<br>已入账保留</p></div></div><div class="command-sample">你要试的问题：<br>“带着收益时，我会继续冒险，还是先回去？”</div><button class="primary" data-play="v4">试玩规则创意版</button>`,'规则设计示意 · 下方可实际试玩');
    case 'compare-rules':return frame('同地图、同危险，只改得分时机',`<div class="compare-cards"><div><span class="pixel-number">A</span><h2>捡到即得分</h2><p>捡一块再碰怪<br>已入账仍是 10</p><button class="secondary" data-play="v3">试玩第三版</button></div><div><span class="pixel-number gold">B</span><h2>带回才算</h2><p>捡一块没存就碰怪<br>背包 10 → 0</p><button class="primary" data-play="v4">试玩第四版</button></div></div><button class="text-link" data-play="lab">打开扩展实验室：保留真实两局记录 ↗</button>`,'课堂观察 · 不预填试玩成绩');
    case 'reference':return frame('一张画面，可以拆成几种修改',`<div class="reference-board"><div><img src="assets/media/slime-layers.png" alt="PPT 第15页史莱姆 UI 分层素材预览"><button class="image-zoom" data-image="assets/media/slime-layers.png">查看原图 ↗</button></div><section><span class="tag gold">PPT 第 15 页</span><h2>先指出是哪一层。</h2><p><b>背景</b>　色调、明暗</p><p><b>人物</b>　大小、轮廓</p><p><b>按钮</b>　位置、标签</p><p><b>数字</b>　字号、对比度</p><small>静态分层图不证明所有游戏功能已完成。</small></section></div>`,'真实项目素材 · 非本课 AI 新生成');
    case 'feedback':return frame('画面反馈 ≠ 计分规则',`<div class="feedback-demo"><div><span class="ore-symbol">◆</span><b>基础反馈</b><p>看 HUD 的数字变化</p></div><div class="enhanced-ore"><span class="ore-symbol">◆</span><em>+10</em><b>强化反馈</b><p>跳字、音效、轻微震动</p></div></div><div class="check-strip">两种表现下，一块矿石仍是 10 分。</div><button class="primary" data-play="lab">打开实验室，切换反馈</button>`,'表现对照示意 · 规则不变');
    case 'share':return frame('把文件带走，再从另一处打开',flow([['复制最终目录','我的矿工 → 我的矿工_交付版'],['压缩 ZIP','右键文件夹 → 压缩 / 发送到'],['全部解压再试','在新位置 → 双击 index.html']])+`<div class="download-ticket"><span>↓</span><div><b>课堂练习包</b><p>4 个阶段 + 1 个故障样本 + 使用说明</p></div><a class="primary" href="practice/矿工练习包.zip" download>下载 ZIP</a></div>`);
    case 'homework':return frame('作业不是背流程，是实际完成三件事',`<div class="assignment-grid"><div><span>01</span><h2>生成第一版</h2><p>空文件夹 → 30 秒星星游戏</p><button class="text-link" data-prompt="homework">起步消息 ↗</button></div><div><span>02</span><h2>改成 45 秒</h2><p>同一任务 → 一次明确修改</p><button class="text-link" data-prompt="homeworkEdit">修改消息 ↗</button></div><div><span>03</span><h2>自己试一遍</h2><p>写下动作、结果和剩余问题</p><button class="text-link" data-homework>填写检查记录 ↗</button></div></div><a class="primary" href="新手操作手册.html" target="_blank" rel="noopener">打开可打印操作手册 ↗</a>`,'课后自己制作 · 不把预制文件当作业');
    case 'workflow':return frame('你刚学的，就是 AI 做 Demo 的工作流',`<div class="final-route">${[['▰','选文件夹','setup',1],['✎','说清需求','first-message',0],['⌘','Agent 写文件','first-message',1],['▶','你打开试玩','first-message',3],['↻','发修改或问题','edit',0],['✓','再次检查','fix',1],['↓','保存分享','practice',0]].map(x=>`<button data-route="${x[2]}/${x[3]}"><span>${x[0]}</span>${x[1]}</button>`).join('')}</div><div class="workflow-sentence"><b>人给目标、做选择、亲自试玩。</b><p>Agent 在授权下读文件、写代码、尝试检查、继续修。</p></div><div class="download-ticket"><div><b>遇到不一致，回对应步骤继续问。</b><p>每一步都能找到操作、消息和预期结果。</p></div><a class="text-link" href="新手操作手册.html" target="_blank" rel="noopener">带走手册 ↗</a></div>`,'点击动作可回到对应教学步骤');
    case 'resources':return frame('AFTER CLASS / 入门视频与参考文章',`<div class="resource-doors"><button data-resources="video"><span>▶</span><div><b>3 个入门视频</b><p>Agent 2 分钟速览 / Codex 初学者讲座 / 提示词片段</p></div></button><button data-resources="article"><span>▤</span><div><b>4 篇官方文章</b><p>安装登录 / 关联文件夹 / 怎么提要求 / Agent 概念</p></div></button><a href="practice/作业提交模板.txt" download><span>✓</span><div><b>作业提交单</b><p>第一版 + 修改版 + 两条消息 + 自己的试玩记录</p></div></a></div><a class="text-link" href="课后参考.html" target="_blank" rel="noopener">单独打开完整参考书架 ↗</a>`,'链接与中文导读可离线看 · 外部内容需联网');
    default:return window.OutlineVisuals?window.OutlineVisuals(s,{D,frame,esc}):'';
  }}
  function render(){
    const c=D.chapters[current],s=c.steps[step];visited.add(c.id);document.body.classList.toggle('scanlines',scan);document.body.classList.toggle('reduced',reduced);
    $('rail').innerHTML=D.chapters.map((x,i)=>`<button data-chapter="${i}" class="${i===current?'active':visited.has(x.id)?'visited':''}" title="${esc(x.name)}" aria-label="第 ${i+1} 关 ${esc(x.name)}" ${i===current?'aria-current="step"':''}>${String(i+1).padStart(2,'0')}</button>`).join('');
    $('main').innerHTML=`<article class="beginner-chapter"><header class="beginner-head"><div><span class="eyebrow">LEVEL ${String(current+1).padStart(2,'0')} / ${c.minutes} MIN</span><h1>${esc(c.title)}</h1><p>${esc(c.subtitle)}</p></div><span class="lesson-token">${String(current+1).padStart(2,'0')}</span></header><nav class="step-tabs" aria-label="本关步骤">${c.steps.map((x,i)=>`<button data-step="${i}" class="${i===step?'active':''}" ${i===step?'aria-current="step"':''}><span>${i+1}</span>${esc(x.name)}</button>`).join('')}</nav><div class="teaching-grid"><div class="teaching-visual">${visual(s)}</div><aside class="instruction-side"><div class="now-heading"><span>现在做什么</span><strong>${esc(s.name)}</strong></div><ol class="action-list">${s.action.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><div class="expected-result"><span>✓ 完成后看到什么</span><p>${esc(s.expected)}</p></div><button class="send-prompt" data-prompt="${s.prompt}"><span>✎ 给 AI 发什么</span><b>查看 / 复制完整消息 ↗</b></button><details class="trouble"><summary>不一样怎么办？</summary><p>${esc(s.help)}</p></details>${s.links?`<a class="official-link" href="${s.links==='setup'?D.sources[0][2]:D.sources[1][2]}" target="_blank" rel="noopener">${s.links==='setup'?'官方安装说明':'官方项目说明'} ↗ <small>课后联网打开</small></a>`:''}${s.case?`<button class="case-button" data-case="${s.case}">⊞ 对应案例：${{mgf:'迷宫饭 · 如何缩小第一步',cube:'Cube · 操作要说清楚',slime:'史莱姆 · 图片怎么拆'}[s.case]}</button>`:''}</aside></div><div class="beginner-takeaway"><span>记住这一点</span><p>${esc(s.tip)}</p></div></article>`;
    document.querySelectorAll('.step-tabs button').forEach((b,i)=>{if(c.steps[i].optional){b.classList.add('optional');b.insertAdjacentHTML('beforeend','<small>选看</small>');}});
    if(s.optional)document.querySelector('.beginner-head .eyebrow').insertAdjacentHTML('afterend','<span class="optional-status">选看补充 · 不另计正课时长</span>');
    $('main').scrollTop=0;$('chapterName').textContent=`${c.name} · ${step+1}/${c.steps.length} 步`;$('pageNumber').innerHTML=`${String(current+1).padStart(2,'0')}<span>/${D.chapters.length}</span>`;
    $('progress').innerHTML=D.chapters.map((x,i)=>`<i class="${i===current?'current':visited.has(x.id)?'done':''}"></i>`).join('');
    $('prevButton').disabled=current===0&&step===0;$('nextButton').innerHTML=step<c.steps.length-1?(D.chapters[current].steps[step+1].optional?'选看补充 <span>→</span>':'下一步 <span>→</span>'):current===D.chapters.length-1?'回到开头 ↺':'下一关 <span>→</span>';
    document.querySelectorAll('[data-preview]').forEach(canvas=>{const b=builds[canvas.dataset.preview],g=TutorialModel.createGame(b.stage,5050,canvas.dataset.preview==='fault');PixelWorld.draw(canvas.getContext('2d'),g,{time:0,reduced:true,danger:b.stage>=3,gold:true});});
    try{history.replaceState(null,'',`#${c.id}/${step+1}`);}catch{}save();
  }
  function go(ch,st=0){if(ch<0||ch>=D.chapters.length)return;current=ch;step=Math.max(0,Math.min(st,D.chapters[ch].steps.length-1));render();}
  function next(){const c=D.chapters[current];if(step<c.steps.length-1)go(current,step+1);else go((current+1)%D.chapters.length);}
  function prev(){if(step>0)go(current,step-1);else if(current>0)go(current-1,D.chapters[current-1].steps.length-1);}
  function info(title,body){$('infoTitle').textContent=title;$('infoBody').innerHTML=body;if(!$('infoDialog').open)$('infoDialog').showModal();}
  async function copy(text,button){try{if(!navigator.clipboard?.writeText)throw Error('clipboard unavailable');await navigator.clipboard.writeText(text);button.textContent='已复制 ✓';}catch{info('请手动复制这段内容',`<p>浏览器限制了自动复制。点击文本框，按 Ctrl + A，然后 Ctrl + C。</p><textarea class="copy-fallback" readonly>${esc(text)}</textarea>`);const ta=$('infoBody').querySelector('textarea');ta.focus();ta.select();}}
  function showPrompt(id){info('给 AI 发什么',`<span class="tag gold">可复制的教学消息 · 不会在此发送</span><pre class="full-prompt">${esc(D.prompts[id])}</pre><button class="primary" data-copy="${id}">复制这条消息</button><p class="prompt-note">复制后，粘贴到对应的 Codex 任务中。涉及截图时先附上你自己的截图，再按实际情况修改文字。</p>`);}
  function dispose(){const f=$('mediaBody').querySelector('iframe');if(f)f.contentWindow?.postMessage({type:'ARCADE_DISPOSE'},'*');const v=$('mediaBody').querySelector('video');if(v){v.pause();v.removeAttribute('src');v.load();}$('mediaBody').replaceChildren();}
  function media(title,badge,html){dispose();returnFocus=document.activeElement;$('mediaTitle').textContent=title;$('mediaBadge').textContent=badge;$('mediaBody').innerHTML=html;$('mediaDialog').showModal();}
  function play(id){if(builds[id])media(`像素矿工 · ${builds[id].name}`,'预制教学文件 · 游戏操作不会调用 AI · 关闭即停止',`<iframe title="${esc(builds[id].name)}可玩游戏" src="${buildPath(id)}"></iframe>`);
    else if(id==='lab')media('像素矿工 · 扩展 A/B 实验室','预置规则实验 · 不计入真实开发历史',`<iframe title="A/B 实验室" src="lab.html?v=B"></iframe>`);
    else if(id==='mgf')media('《迷宫饭》流程片段','PPT 第 13 页内嵌视频 · 34.5 秒 · 项目名沿用 PPT 推断',`<video controls preload="metadata" src="assets/media/mgf-highlight.mp4"></video><p class="media-caption">看入口、战斗、选择之后能否继续。视频证明录到的流程，不证明完整制作过程、长期留存或移动端全部交互。</p>`);
    else if(['pixel','racing'].includes(id))media(id==='pixel'?'2D 像素作品':'3D 竞速作品','原目录作品副本 · 未核验开发耗时或完整会话',`<iframe title="现有可玩作品" src="assets/demos/${id==='pixel'?'pixel-fighter':'racing-3d'}.html"></iframe>`);
  }
  function caseInfo(id){const content={
    mgf:['迷宫饭：第一条需求为什么要小',`<img class="case-thumb" src="assets/media/mgf-landscape.png" alt="迷宫饭录屏抽帧"><p>现有片段有酒馆、地牢战斗、事件或成长选择。这么长的流程，不要一次都塞进新人的第一条需求。</p><p>教学拆法：先要求“从入口进入一场战斗，结束后能继续”，做完再加别的系统。这是本课的拆解示例，不是原项目历史提示词。</p><button class="primary" data-play="mgf">播放 PPT 内嵌视频</button><details><summary>素材与证据说明</summary><p>PPT 第 10–13 页；视频为原 PPT 内嵌媒体。项目名沿用原 PPT 本地记录推断，不据此宣称全部流程或所有平台已验证。</p></details>`],
    cube:['Cube：操作经过决定问题能否被复现',`<table class="case-evidence"><thead><tr><th>实际做过什么</th><th>PPT 记录中的观察</th></tr></thead><tbody><tr><td>点击形状，再点棋盘</td><td>没有放置</td></tr><tr><td>拖动 3×3 块到合法区域</td><td>能放置、消除，订单更新</td></tr><tr><td>切换关卡</td><td>没有确认就重置资源，有误操作风险</td></tr><tr><td>体验前三关</td><td>未见完整胜利结算，不等于通关</td></tr></tbody></table><p>对新人有用的问法：“我是点击还是拖动？从哪里到哪里？最后看见了什么？”不要把操作方式省掉。</p><details><summary>来源</summary><p>用户提供 PPT 第 19 页真实验收记录；拖拽预览在手指上方 120px。本课没有重新运行 Cube，不把原记录当成本次验证。</p></details>`],
    slime:['史莱姆：说清改哪一层',`<div class="case-pair"><img src="assets/media/slime-scene.png" alt="史莱姆完整场景"><img src="assets/media/slime-layers.png" alt="UI 分层预览"></div><p>背景、人物区域、血条、按钮可以分别讨论。给 AI 图时指出具体区域，再说明“只改这块，不动规则”。</p><p>像“四射、弹射、穿透”这样的玩法词，也要说明触发条件和次数，不能让 AI 自己猜。</p><details><summary>来源与限制</summary><p>PPT 第 14–15 页。第 14 页对话是保存文本重建，不是原始 GUI。第 15 页分层图证明资源产物，不证明全部法球功能、性能和手感。</p><button class="text-link" data-image="assets/media/slime-rebuilt-dialogue.png">查看标注来源的重建对话</button></details>`]
  };info(...content[id]);}
  function homework(){info('自己的试玩记录',`<p>必须交：第一版游戏、修改版游戏、发给 AI 的两条消息和自己的试玩记录。只有实际检查过才勾选，不能把课堂预制文件当作业。</p><div class="homework-checks">${['我从空文件夹生成了第一版','我能找到并打开入口文件','捡一颗只加 10，不能重复加分','30 秒到 0 后停止并能重开','修改后新一局显示 45 秒','解压到另一个位置仍能玩'].map((x,i)=>`<label><input type="checkbox" data-check="${i}" ${checks.includes(i)?'checked':''}>${x}</label>`).join('')}</div><label class="note-label" for="practiceNote">我怎么操作、看到了什么、还有什么没检查？</label><textarea id="practiceNote" placeholder="例如：按右上方向捡第一颗，0→10；离开再回来没有增加。45 秒结束后人物不再移动。">${esc(practiceNote)}</textarea><div class="button-row"><button class="primary" data-export-note>下载我的检查记录</button><a class="secondary" href="practice/作业提交模板.txt" download>下载完整作业提交单</a></div><p>选做：只增加一条自己的规则，保留旧版，写出实际试玩差别。提交时间由讲师安排。</p>`);}
  function resources(filter){info('课后参考 · '+(filter==='video'?'入门视频':'官方文章'),`<div class="reference-filter"><button data-resources="video">视频</button><button data-resources="article">文章</button><a href="课后参考.html" target="_blank" rel="noopener">单独打开完整书架 ↗</a></div><p>核对日期：2026-09-04。先按“看什么”选内容，不必全部学完。点击才访问外部页面；视频没有下载到离线包。</p><div class="reference-list">${window.COURSE_REFERENCES.items.filter(x=>x.kind===filter).map(x=>`<article><div class="reference-meta">${chip(x.level,'gold')}<span>${esc(x.publisher)} · ${esc(x.time)}</span></div><h3>${esc(x.title)}</h3><p><b>看什么：</b>${esc(x.focus)}</p><p class="reference-scope">${esc(x.scope)}</p><a href="${esc(x.url)}" target="_blank" rel="noopener">${filter==='video'?'联网打开视频来源':'联网阅读原文'} ↗</a><details><summary>语言与核对范围</summary><p>${esc(x.language)}。${esc(x.verified)}</p></details></article>`).join('')}</div>`);}
  function downloadText(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  document.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;if(t.dataset.chapter!==undefined){go(+t.dataset.chapter);if($('mapDialog').open)$('mapDialog').close();}if(t.dataset.step!==undefined)go(current,+t.dataset.step);if(t.dataset.prompt)showPrompt(t.dataset.prompt);if(t.dataset.copy)copy(D.prompts[t.dataset.copy],t);if(t.dataset.play)play(t.dataset.play);if(t.dataset.case)caseInfo(t.dataset.case);if(t.dataset.image)media('项目素材原图','来源：用户 PPT 提取媒体 · 原图未改',`<img class="full-image" src="${esc(t.dataset.image)}" alt="PPT 来源素材原图">`);if(t.hasAttribute('data-homework'))homework();if(t.hasAttribute('data-export-note'))downloadText('我的试玩记录.txt',`我的 AI 游戏练习记录\n${['从空文件夹生成第一版','能找到并打开入口','计分与重复拾取','30 秒结束与重开','改为 45 秒','新目录解压打开'].map((x,i)=>(checks.includes(i)?'[已人工检查] ':'[未检查] ')+x).join('\n')}\n\n实际观察：\n${practiceNote||'尚未填写'}\n`);if(t.dataset.close)$(t.dataset.close).close();});
  document.addEventListener('change',e=>{if(e.target.dataset.check!==undefined){const i=+e.target.dataset.check;checks=e.target.checked?[...new Set([...checks,i])]:checks.filter(x=>x!==i);save();}});
  document.addEventListener('click',e=>{const t=e.target.closest('[data-resources]');if(t)resources(t.dataset.resources);});
  document.addEventListener('input',e=>{if(e.target.id==='practiceNote'){practiceNote=e.target.value;save();}});
  $('prevButton').onclick=prev;$('nextButton').onclick=next;$('closeMedia').onclick=()=>{$('mediaDialog').close();};$('mediaDialog').addEventListener('close',()=>{dispose();returnFocus?.focus?.();});
  $('mapButton').onclick=()=>{$('mapGrid').innerHTML=D.chapters.map((c,i)=>`<button class="map-level ${i===current?'active':''}" data-chapter="${i}"><strong>${String(i+1).padStart(2,'0')}</strong><span>${esc(c.name)}</span><small>${c.minutes} MIN · ${c.steps.length} STEPS</small></button>`).join('');$('mapDialog').showModal();};
  $('notesButton').onclick=()=>info('本关讲师备注',`<span class="tag gold">${D.chapters[current].minutes} 分钟 · ${esc(D.chapters[current].name)}</span><p>${esc(D.chapters[current].note)}</p><p>课堂展示预制文件，不会请求 AI。请按“当前操作 → 看到结果 → 下一步”讲，不把示意图当作历史记录。</p>`);
  $('sourcesButton').onclick=()=>info('素材与操作来源',`<ul class="source-list">${D.sources.map(x=>`<li><b>${esc(x[0])}</b><br>${esc(x[1])}${x[2]?`<br><a href="${x[2]}" target="_blank" rel="noopener">查看官方来源 ↗</a>`:''}</li>`).join('')}</ul><p>更完整清单见随包 SOURCES.md。外部说明链接课后联网打开，课堂媒体均在本地。</p>`);
  document.addEventListener('click',e=>{const t=e.target.closest('[data-route]');if(!t)return;const [id,st]=t.dataset.route.split('/');go(D.chapters.findIndex(c=>c.id===id),Number(st)||0);});
  $('examplesButton').onclick=()=>info('可选案例抽屉',`<p>用具体操作对照课堂问题；复杂成品不等于第一条需求的范围。</p><div class="drawer-actions"><button data-case="mgf">迷宫饭：缩小第一步</button><button data-case="cube">Cube：如何描述操作</button><button data-case="slime">史莱姆：参考和分层</button><button data-play="pixel">打开现有 2D 作品</button><button data-play="racing">打开现有 3D 作品</button><button data-play="lab">打开矿工 A/B 实验室</button></div>`);
  $('settingsButton').onclick=()=>{info('显示设置',`<label class="setting-row"><input id="scanSetting" type="checkbox" ${scan?'checked':''}>轻量扫描线</label><label class="setting-row"><input id="motionSetting" type="checkbox" ${reduced?'checked':''}>减少动态效果</label><p>课堂正文与操作图始终保持可读。课件不自动播放声音。</p>`);$('scanSetting').onchange=e=>{scan=e.target.checked;render();};$('motionSetting').onchange=e=>{reduced=e.target.checked;render();};};
  $('fullscreenButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{info('全屏','<p>浏览器未允许全屏。可以使用浏览器的 F11 全屏，或继续当前窗口演示。</p>');}};
  document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='ArrowRight'){e.preventDefault();next();}if(e.key==='ArrowLeft'){e.preventDefault();prev();}});
  window.addEventListener('hashchange',()=>{const parts=location.hash.slice(1).split('/'),i=D.chapters.findIndex(c=>c.id===parts[0]);if(i>=0)go(i,(Number(parts[1])||1)-1);});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){$('mediaBody').querySelector('video')?.pause();$('mediaBody').querySelector('iframe')?.contentWindow?.postMessage({type:'ARCADE_PAUSE'},'*');}});
  render();
})();
