(function(){
  'use strict';
  const D=window.ARCADE_COURSE,$=id=>document.getElementById(id),main=$('main');
  let saved={};try{saved=JSON.parse(localStorage.getItem('arcade-course-v1')||'{}')||{};}catch{}
  const valid=id=>D.chapters.some(c=>c.id===id),hash=location.hash.slice(1);
  let current=D.chapters.findIndex(c=>c.id===(valid(hash)?hash:valid(saved.chapter)?saved.chapter:'start'));
  const visited=new Set(Array.isArray(saved.visited)?saved.visited:[]);
  let flow=0,taskShown=1,caseIndex=0,decision='',evidence='',checks=new Set(),heroRaf=0,returnFocus=null;
  let reduced=typeof saved.reduced==='boolean'?saved.reduced:matchMedia('(prefers-reduced-motion: reduce)').matches;
  let scanlines=saved.scanlines===true;
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function save(){try{localStorage.setItem('arcade-course-v1',JSON.stringify({chapter:D.chapters[current].id,visited:[...visited],reduced,scanlines}));}catch{}}
  function settings(){document.body.classList.toggle('reduced',reduced);document.body.classList.toggle('scanlines',scanlines);}
  function head(c){return `<header class="chapter-head"><span class="eyebrow">${c.kicker} <span class="muted">/ ${c.minutes} MIN</span></span><h1>${c.title}</h1><p>${c.subtitle||''}</p></header>`;}
  function hero(){return `<section class="hero"><div class="hero-copy"><span class="eyebrow">LEVEL 01 / A PLAYABLE IDEA</span><h1>把一个想法<br>变成能玩的<br><span class="gold underlined">第一关。</span></h1><p>用一个真实可玩的 Demo，<br>看懂 AI 怎样协助制作游戏，<br>也看懂制作人该做哪些判断。</p><button class="primary" data-media="labA">进入矿场 · 先玩 45 秒 <span>→</span></button><div class="hero-mini"><span>原创玩法实验室</span><span>真实项目成果</span><span>无需联网 / Codex</span></div><div class="hero-bottom-label">LESS TALK. MORE PLAYABLE EVIDENCE.</div></div><div class="hero-visual"><div class="arcade-frame"><div class="arcade-top"><span>PIXEL MINER</span><b>READY TO PLAY</b></div><canvas id="heroCanvas" width="960" height="540" aria-label="像素矿场预览，点击进入矿场开始真实试玩"></canvas><div class="arcade-caption"><strong>像素矿工：再拿一块。</strong><small>PRESS<br>START →</small></div><span class="coin-badge">45s<br>1 RUN</span></div><div class="pixel-ticket"><span>?</span><div><strong>再拿一块，还是先回去？</strong><small>一条规则的改变，可能就是一种新的选择。</small></div></div></div></section>`;}
  function gallery(){return `<div class="gallery"><article class="feature-project"><button class="project-image" data-media="mgf" aria-label="播放迷宫饭成果视频"><img src="assets/media/mgf-landscape.png" alt="PPT 中的迷宫饭酒馆录屏抽帧"><span class="play-medallion">▶ 播放实际成果 / 约 35 秒</span></button><div class="project-info"><span class="tag">项目录屏剪辑 · PPT 内嵌媒体</span><h2>《迷宫饭》Debug 流程</h2><p>从酒馆进入地牢，做出选择，再回到战斗。<br>先看一圈能否连通，而不是先谈所有系统。</p><div class="project-source">PPT 第 10–13 页；项目名称沿用原资料推断。只证明录屏呈现的流程。</div></div></article><div class="side-projects"><article class="compact-project"><button class="project-image" data-media="pixel" aria-label="试玩 2D 像素作品"><img src="assets/media/pixel-fighter.png" alt="现有 2D 像素对战作品封面"></button><div><span class="tag gold">本地可玩作品</span><h3>2D 像素对战</h3><p>按实际操作说明试玩，观察输入与反馈。</p><button class="text-link" data-media="pixel">打开真实作品 ↗</button></div></article><article class="compact-project"><button class="project-image" data-media="racing" aria-label="试玩 3D 作品"><img src="assets/media/racing-3d.png" alt="现有 3D 作品封面"></button><div><span class="tag gold">本地可玩作品</span><h3>3D 场景与竞速</h3><p>看移动和空间体验，不将画面等同于成品质量。</p><button class="text-link" data-media="racing">打开真实作品 ↗</button></div></article></div></div>`;}
  function why(){return `<div class="why-board"><article class="why-item"><div class="big-number">01</div><h2>规则真的能走通吗？</h2><p>“采集 → 装进背包 → 回基地入账”，纸面上只是一行字。Demo 让你检查每一步是否真的发生。</p><div class="observation">现场检查：捡一块矿，背包是否 +10？回基地后，这 10 分去了哪里？</div></article><article class="why-item"><div class="big-number">02</div><h2>问题出在哪里？</h2><p>玩家不回基地，可能不是玩法无聊，而是没看见背包、没理解损失，或者找不到回程。</p><div class="observation">观察对象：行动、界面和结果。先记录现象，再判断原因。</div></article><article class="why-item"><div class="big-number">03</div><h2>下一步值得做什么？</h2><p>大家面对同一段操作讨论，才能区分“修一个提示”和“加十个系统”，哪个更接近当前问题。</p><div class="observation">最小下一步：只改基地提示，再看是否更容易理解。</div></article></div><div class="limit-strip"><strong>它还不能证明</strong><span>长期留存、商业价值、完整内容量和生产质量。一个原型能跑，是验证的开始，不是结论。</span></div>`;}
  function roles(){return `<div class="roles-board"><section class="role-side"><header><h2>制作人 / 你</h2><span>PLAYER 1</span></header><div class="role-item"><b>定体验</b><p>要让玩家有“带着收益回程”的紧张感，而不只是移动捡东西。</p></div><div class="role-item"><b>定边界</b><p>这一轮只改入账规则；不顺手加商店、装备、剧情与新关卡。</p></div><div class="role-item"><b>做判断</b><p>亲自试玩，记录问题；决定保留、调整或停止，不能只接受“完成了”。</p></div></section><div class="coop">+</div><section class="role-side ai"><header><h2>AI / 执行工具</h2><span>CO-OP</span></header><div class="role-item"><b>理解项目，拆小任务</b><p>读取相关文件，说明现有规则、拟改内容和不确定项。</p></div><div class="role-item"><b>实现可玩的变化</b><p>在人确认的范围内修改规则、界面或资源，输出可运行版本。</p></div><div class="role-item"><b>协助检查，报告边界</b><p>运行检查、列出结果与风险；没有执行的验收，要明确写“未验证”。</p></div></section></div><p class="role-footnote"><strong>一个区别就够了：</strong>模型可以理解和生成内容；Codex 这类带工具的执行者可以在授权项目里行动。课堂不需要打开它，也不把预置实验伪装成实时调用。</p>`;}
  function workflow(){const w=D.workflow[flow];return `<div class="workflow-nav" role="tablist" aria-label="工作流节点">${D.workflow.map((s,i)=>`<button role="tab" aria-selected="${flow===i}" data-flow="${i}" class="${flow===i?'active':''}"><span>0${i+1}</span>${s.name}</button>`).join('')}</div><div class="workflow-detail"><div class="artifact-title"><span>0${flow+1}</span><h2>${w.artifact}</h2><p>教学示例产物<br>不是原始 AI 会话或历史版本记录</p></div><div class="artifact-content"><span class="input-label">${w.input}</span><blockquote>${w.body}</blockquote><p>${w.check}</p><div class="artifact-next">→ ${w.next}</div>${flow===2?'<div class="button-row"><button class="text-link" data-media="labB">打开这里对应的可玩示例 ↗</button></div>':''}</div></div>`;}
  function experiment(){return `<div class="experiment-board"><section class="experiment-version"><div class="experiment-top"><span>A</span><div><h2>即时得分</h2><small>捡到，就属于你</small></div></div><div class="score-route"><span>采集一块<small>规则示意</small></span><i>→</i><span>已入账 <strong>+10</strong></span></div><p>遇险会回到基地，但已入账分数不丢。<br>你更可能追逐下一块矿石。</p><button class="secondary" data-media="labA">试玩 A 版 →</button></section><section class="experiment-version b"><div class="experiment-top"><span>B</span><div><h2>带回才算</h2><small>收益在身上，选择也在你手上</small></div></div><div class="score-route"><span>采集<small>背包 +10</small></span><i>→</i><span>回基地<small>转入已入账</small></span><i>→</i><strong>10</strong></div><p>遇险丢背包，已入账分数保留。<br>“继续拿”开始有了机会成本。</p><button class="primary" data-media="labB">试玩 B 版 →</button></section></div><div class="experiment-observe"><span><b>看三个现象：</b>什么时候回基地？遇险丢了多少？为什么决定再拿一块？</span><span class="tag gold">预置规则实验 · 非实时 AI</span></div>`;}
  function task(){return `<div class="task-layout"><section class="bad-task"><span class="tag red">无法直接验收</span><h2>“把采矿做得<br>更刺激一点。”</h2><p>更快？更多敌人？更容易丢收益？<br>这些方案会产生不同体验。<br>先选你真正想验证的那个。</p><span class="task-count">${taskShown} / 4 FIELDS REVEALED</span></section><section class="good-task"><span class="tiny-label">TASK CARD / 人工编写的教学模板</span>${D.taskParts.map((p,i)=>i<taskShown?`<div class="task-part"><b>${p.label}</b><p>${p.text}</p></div>`:`<div class="task-locked">${p.label}　·　等待展开</div>`).join('')}<div class="task-actions"><button class="primary" id="revealTask" ${taskShown===4?'disabled':''}>${taskShown===4?'任务已完整':'展开下一项 →'}</button><button class="text-link" id="copyCourseTask">复制完整任务</button><span class="status" id="taskCopyStatus" role="status"></span></div></section></div>`;}
  function cases(){const c=D.cases[caseIndex];return `<div class="case-tabs" role="tablist" aria-label="真实项目案例">${D.cases.map((t,i)=>`<button role="tab" aria-selected="${caseIndex===i}" class="${caseIndex===i?'active':''}" data-case="${i}">${t.name}</button>`).join('')}</div><div class="case-layout"><button class="case-image" data-image="${c.image}" aria-label="放大查看案例原图"><img src="${c.image}" alt="${c.name}，${c.badge}"><span class="zoom-hint">⛶ 放大原图</span></button><div class="case-text"><span class="tag ${caseIndex===1?'gold':''}">${c.badge}</span><h2>${c.title}</h2><p>${c.text}</p><div class="evidence-bound yes">✓ ${c.verified}</div><div class="evidence-bound no">! ${c.limit}</div><div class="project-source">${c.source}</div><div class="button-row">${c.action==='video'?'<button class="text-link" data-media="mgf">播放对应录屏 ↗</button><button class="text-link" data-image="assets/media/mgf-portrait.png">看竖屏画面 ↗</button>':c.action==='slime'?'<button class="text-link" data-image="assets/media/slime-scene.png">看完整画面 ↗</button><button class="text-link" data-image="assets/media/slime-original.png">看原始评审画面 ↗</button>':'<button class="text-link" data-image="assets/media/slime-scene.png">看素材产物，不推断功能 ↗</button>'}</div></div></div>`;}
  function verify(){return `<table class="evidence-table"><thead><tr><th>做了什么</th><th>观察到的稳定结果</th><th>可以怎样下结论</th></tr></thead><tbody>${D.evidence.map(r=>`<tr>${r.map(s=>`<td>${s}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="project-source">来源：PPT 第 18–19 页，Cube 前三关操作记录的摘述；未取得可在本课运行的 Cube 工程。</div><div class="verify-bottom"><div><span class="manual-label">矿工现场检查 / 下方仅由讲师手动标记，并非自动测试结果</span><div class="manual-checks">${['采集后的分数正确','遇险只损失背包','回基地后正确入账'].map((s,i)=>`<label><input type="checkbox" data-check="${i}" ${checks.has(i)?'checked':''}>${s}</label>`).join('')}</div></div><button class="secondary" data-media="labB">打开 B 版，实际验收 ↗</button></div>`;}
  function decisionView(){const d=D.decisions[decision];return `<div class="decision-layout"><div class="decision-options">${[['keep','01','保留','再验证这个方向'],['adjust','02','调整','只解决一个问题'],['stop','03','停止','不再追加功能']].map(([k,n,t,s])=>`<button data-decision="${k}" class="decision-button ${decision===k?'active':''}"><span>${n}</span><div><b>${t}</b><small>${s}</small></div></button>`).join('')}</div><section class="decision-output"><span class="tiny-label">NEXT ROUND / 制作人任务卡</span>${d?`<h2>${d.title}</h2><p>${d.task}</p><textarea id="evidenceInput" rows="2" placeholder="填写刚才真正看到的一条现象；没有观察到，就写待验证。" aria-label="本次观察证据">${esc(evidence)}</textarea><div class="button-row"><button class="primary" id="copyDecision">复制任务卡 →</button><button class="secondary" id="downloadDecision">保存为 Markdown</button><span id="decisionStatus" class="status" role="status"></span></div>`:'<p class="empty-message">先说出一条真实观察，<br>再选择下一步。<br>不要因为“已经做了”，就默认继续。</p><span class="offline-stamp">没有 AI 调用，也没有预填用户结论</span>'}</section></div>`;}
  const views={hero,gallery,why,roles,workflow,experiment,task,cases,verify,decision:decisionView};
  function render(){
    cancelAnimationFrame(heroRaf);
    const c=D.chapters[current];visited.add(c.id);settings();save();
    main.innerHTML=c.type==='hero'?hero():`<section class="chapter">${head(c)}<div class="chapter-body">${views[c.type]()}</div><div class="lesson-bottom"><span>TAKE AWAY</span><p>${c.takeaway}</p></div></section>`;
    $('rail').innerHTML=D.chapters.map((c,i)=>`<button title="${c.name} · ${c.minutes} 分钟" aria-label="第 ${i+1} 关 ${c.name}" ${i===current?'aria-current="step"':''} data-go="${i}" class="${i===current?'active':visited.has(c.id)?'visited':''}">${String(i+1).padStart(2,'0')}</button>`).join('');
    $('pageNumber').innerHTML=`${String(current+1).padStart(2,'0')}<span>/10</span>`;
    $('chapterName').textContent=`${c.name} · ${c.minutes} MIN`;
    $('progress').innerHTML=D.chapters.map((c,i)=>`<i class="${i===current?'current':visited.has(c.id)?'done':''}"></i>`).join('');
    $('prevButton').disabled=current===0;$('nextButton').innerHTML=current===9?'选择关卡 <span>▦</span>':'下一关 <span>→</span>';
    main.scrollTop=0;bind();
    if(c.type==='hero'){
      const canvas=$('heroCanvas'),ctx=canvas.getContext('2d'),g=MinerModel.createGame('A');g.player.x=330;g.player.y=287;
      const tick=now=>{PixelWorld.draw(ctx,g,{time:reduced?0:now/1000,reduced});if(!reduced)heroRaf=requestAnimationFrame(tick);};tick(0);
    }
  }
  function go(i){if(i<0||i>=10)return;current=i;const id=D.chapters[i].id;if(location.hash!==`#${id}`){try{history.replaceState(null,'',`#${id}`);}catch{location.hash=id;}}render();}
  function bind(){
    document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{go(+b.dataset.go);$('mapDialog').close();});
    main.querySelectorAll('[data-media]').forEach(b=>b.onclick=()=>openMedia(b.dataset.media));
    main.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>openImage(b.dataset.image));
    main.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>{flow=+b.dataset.flow;render();});
    main.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{caseIndex=+b.dataset.case;render();});
    main.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>{decision=b.dataset.decision;render();});
    main.querySelectorAll('[data-check]').forEach(b=>b.onchange=()=>b.checked?checks.add(+b.dataset.check):checks.delete(+b.dataset.check));
    if($('revealTask'))$('revealTask').onclick=()=>{taskShown=Math.min(4,taskShown+1);render();};
    if($('copyCourseTask'))$('copyCourseTask').onclick=()=>copy(fullTask(),'taskCopyStatus');
    if($('evidenceInput'))$('evidenceInput').oninput=e=>evidence=e.target.value;
    if($('copyDecision'))$('copyDecision').onclick=()=>copy(decisionText(),'decisionStatus');
    if($('downloadDecision'))$('downloadDecision').onclick=()=>{const blob=new Blob([decisionText()],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='矿工实验_下一轮任务卡.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('decisionStatus').textContent='已发起保存';};
  }
  function fullTask(){return '【人工编写的教学任务模板，不是 AI 回答】\n项目：像素矿工，原生 HTML / CSS / JavaScript。\n先只读相关文件并复述理解，暂不修改。\n'+D.taskParts.map(p=>p.label+'\n'+p.text).join('\n\n')+'\n\n先给最小计划，确认后再执行。完成后回报改动、实测结果与未验证项。';}
  function decisionText(){const d=D.decisions[decision];return `# 矿工实验：下一轮任务卡\n\n决策：${d.label}\n\n本次观察：${evidence.trim()||'待验证；尚未填写实际观察，不作为结论。'}\n\n下一步：${d.task}\n\n验收与边界：${d.criterion}\n\n说明：教学模板 + 讲师记录；不包含自动生成的玩家数据，不是 AI 回复。`;}
  async function copy(text,status){try{await navigator.clipboard.writeText(text);$(status).textContent='已复制';}catch{const el=document.createElement('textarea');el.value=text;el.style.position='fixed';el.style.top='-9999px';document.body.appendChild(el);el.select();let ok=false;try{ok=document.execCommand('copy');}catch{}el.remove();if(ok)$(status).textContent='已复制';else{showInfo('手动复制任务卡',`<p>浏览器未开放剪贴板，请选中下面的文字后按 Ctrl+C。</p><textarea readonly style="width:100%;height:260px;background:#142330;color:#eee;padding:15px">${esc(text)}</textarea>`);$(status).textContent='可手动复制';}}}
  const resources={
    labA:{title:'像素矿工：再拿一块 · 原创玩法实验室',badge:'教学预置实验 · 非实时 AI · 关闭即停止',src:'lab.html?v=A',type:'lab'},
    labB:{title:'像素矿工：再拿一块 · 原创玩法实验室',badge:'教学预置实验 · 非实时 AI · 关闭即停止',src:'lab.html?v=B',type:'lab'},
    mgf:{title:'《迷宫饭》Debug：从入口到可玩闭环',badge:'PPT 第 13 页内嵌录屏剪辑 · 不是现场运行的游戏',src:'assets/media/mgf-highlight.mp4',type:'video'},
    pixel:{title:'2D 像素对战 · 现有可玩作品',badge:'来源：原文件夹 2D像素作品-play.html · 开发耗时与完整会话未核验',src:'assets/demos/pixel-fighter.html',type:'embed'},
    racing:{title:'3D 场景与竞速 · 现有可玩作品',badge:'来源：原文件夹 3D作品-play.html · 不作为完整生产质量证明',src:'assets/demos/racing-3d.html',type:'embed'}
  };
  function showMedia(title,badge,html){returnFocus=document.activeElement;$('mediaTitle').textContent=title;$('mediaBadge').textContent=badge;$('mediaBody').innerHTML=html;$('mediaDialog').showModal();$('closeMedia').focus();cancelAnimationFrame(heroRaf);}
  function openMedia(key){const r=resources[key];if(!r)return;let src=r.src;if(r.type==='lab'&&reduced)src+='&motion=off';
    const html=r.type==='video'?`<video controls playsinline preload="metadata" poster="assets/media/mgf-landscape.png" src="${src}"></video><p class="media-caption">点击播放，音量由讲师控制。观察：入口 → 选择 → 继续战斗。视频来自 PPT 内嵌剪辑；不推断未展示功能。</p>`:`<iframe src="${src}" title="${r.title}" allow="fullscreen; gamepad" allowfullscreen></iframe><p class="media-caption">${r.type==='lab'?'方向键 / WASD / 点击地面移动；P 暂停。切出窗口会暂停，切换版本将重新开局。':'请按作品内操作说明试玩；点击游戏画面获取键盘焦点。'} <a href="${src}" target="_blank" rel="noopener" style="color:#f5ce7c;text-decoration:underline">独立打开 ↗</a> · 关闭演示后回到本关。</p>`;
    showMedia(r.title,r.badge,html);
    const v=$('mediaBody').querySelector('video');if(v)v.addEventListener('error',()=>{const p=document.createElement('p');p.className='media-error';p.textContent='视频未能加载。请确认已完整复制 assets/media 文件夹；可返回本关查看 PPT 抽帧。';$('mediaBody').prepend(p);});
  }
  function openImage(src){showMedia('查看素材原图','PPT 提取素材 · 证据说明以课程正文为准',`<img class="full-image" src="${src}" alt="PPT 素材原图，保留原有标记与说明">`);}
  function disposeMedia(){const frame=$('mediaBody').querySelector('iframe');if(frame)frame.contentWindow?.postMessage({type:'ARCADE_DISPOSE'},'*');const v=$('mediaBody').querySelector('video');if(v){v.pause();v.removeAttribute('src');v.load();}$('mediaBody').replaceChildren();if(current===0)render();returnFocus?.focus();}
  $('closeMedia').onclick=()=>$('mediaDialog').close();$('mediaDialog').addEventListener('close',disposeMedia);
  function map(){ $('mapGrid').innerHTML=D.chapters.map((c,i)=>`<button class="map-level ${i===current?'active':''}" data-go="${i}"><strong>${String(i+1).padStart(2,'0')}</strong><span>${c.name}</span><small>${c.minutes} MIN${visited.has(c.id)?' / VIEWED':''}</small></button>`).join('');$('mapDialog').showModal();bind(); }
  function showInfo(title,html){$('infoTitle').textContent=title;$('infoBody').innerHTML=html;if(!$('infoDialog').open)$('infoDialog').showModal();}
  $('mapButton').onclick=map;$('prevButton').onclick=()=>go(current-1);$('nextButton').onclick=()=>current===9?map():go(current+1);
  $('notesButton').onclick=()=>showInfo(`讲师备注 · 第 ${current+1} 关`, `<span class="tag gold">建议 ${D.chapters[current].minutes} 分钟 · 讲师操作，学员观看</span><p>${D.chapters[current].note}</p><p class="small">课程目标是看懂方法与判断，不承诺仅靠观看就能独立开发。本页面不会调用 AI。</p>`);
  $('sourcesButton').onclick=()=>showInfo('素材与证据来源',`<ol class="source-list"><li><b>原创玩法实验室</b><br>本次新建的教学游戏，A/B 为预置规则切换。游戏数据只来自已完成的实际操作。流程图与任务卡属于教学编写，不是历史 AI 对话。</li><li><b>《迷宫饭》 / MGF</b><br>来源：Codex游戏开发工作流与入门_内部培训.pptx 第 10–13 页，原录屏日期 2026-05-25 / 05-28。使用 PPT 内嵌剪辑与抽帧。项目名为原资料推断，未取得原始 session / cwd。</li><li><b>史莱姆 / P0728</b><br>PPT 第 14–15 页。会话图根据保存文本重建，非原始 GUI；完整画面与分层预览只证明对应素材存在，不证明全部法球运行效果。</li><li><b>Cube 验收记录</b><br>PPT 第 18–19 页摘述。体验前三关不等于通关；本课没有 Cube 可玩工程。</li><li><b>2D / 3D 本地作品</b><br>复制自原文件夹的 2D像素作品-play.html 与 3D作品-play.html。保留作品本体，不声明制作时长或一次生成成功率。</li><li><b>字体与制作说明</b><br>Noto Sans SC / Press Start 2P，随包附 SIL Open Font License。详细文件映射、限制和原始文件校验见 SOURCES.md。</li></ol>`);
  $('settingsButton').onclick=()=>{showInfo('显示设置',`<label class="setting-row"><input type="checkbox" id="scanSetting" ${scanlines?'checked':''}><span>轻量扫描线<br><small class="muted">仅改变显示效果，投屏时可以关闭。</small></span></label><label class="setting-row"><input type="checkbox" id="motionSetting" ${reduced?'checked':''}><span>减少动态效果<br><small class="muted">关闭装饰动画；新打开的实验室沿用该设置。</small></span></label><p class="small">默认静音。游戏音效需要在实验室里主动开启。</p>`);$('scanSetting').onchange=e=>{scanlines=e.target.checked;settings();save();};$('motionSetting').onchange=e=>{reduced=e.target.checked;settings();save();if(current===0)render();};};
  $('fullscreenButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{showInfo('全屏提示','<p>当前浏览器未允许网页全屏。可以按 F11，或使用浏览器菜单进入全屏；课件仍可正常使用。</p>');}};
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
  document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.target.matches('textarea,input,select'))return;if(e.key==='ArrowRight'){e.preventDefault();go(current+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(current-1);}if(e.key==='Home'){e.preventDefault();go(0);}if(e.key==='End'){e.preventDefault();go(9);}});
  window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(valid(id))go(D.chapters.findIndex(c=>c.id===id));});
  window.addEventListener('message',e=>{const f=$('mediaBody').querySelector('iframe');if(f&&e.source===f.contentWindow&&e.data?.type==='ARCADE_CLOSE')$('mediaDialog').close();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){$('mediaBody').querySelector('video')?.pause();$('mediaBody').querySelector('iframe')?.contentWindow?.postMessage({type:'ARCADE_PAUSE'},'*');cancelAnimationFrame(heroRaf);}else if(current===0&&!$('mediaDialog').open)render();});
  render();
})();
