/* Curated public learning links. No remote media is loaded by the course. */
window.COURSE_REFERENCES={checked:'2026-09-04',items:[
{id:'agent-video',kind:'video',level:'先看这个',title:'AI 智能体介绍：2 分钟速览',original:'AI agents explained (2-minute AI with Google)',publisher:'Google Cloud',language:'中文介绍页；视频语言/字幕以播放器为准',time:'官方标注 2:11',url:'https://cloud.google.com/discover/what-are-ai-agents?hl=zh-CN',focus:'打开文章顶部的 2:11 视频，先理解“给目标 → 使用工具 → 执行动作”。再联系矿工例子：AI 写文件，你打开试玩。',scope:'对应第 1 关。页面还包含云产品介绍，本课不需要注册云服务。',verified:'已核对官方中文页面及其视频入口；未逐分钟审看视频。'},
{id:'codex-beginner',kind:'video',level:'入门选看',title:'Codex for Beginners',original:'Codex for Beginners',publisher:'OpenAI Academy',language:'英文讲座；中文字幕可用性未核验',time:'2026-04-22 发布 / 讲座回放',url:'https://academy.openai.com/public/videos/codex-for-beginners-2026-04-22',focus:'完成本课第一版后，再看官方初学者讲座。带着问题看：任务在哪里开始？怎样提供项目？生成后怎样检查？',scope:'对应第 2–5 关。较早界面可能不同，以当前官方操作说明为准。',verified:'已核对页面、讲者与回放说明；未逐分钟审看。'},
{id:'codex-prompt-video',kind:'video',level:'按需选看',title:'Getting started with Codex：提示词片段',original:'Getting started with Codex',publisher:'OpenAI / YouTube',language:'英文；字幕/自动翻译以播放器为准',time:'建议选看 16:26–27:02',url:'https://www.youtube.com/watch?v=px7XlbYgk7I&t=986s',focus:'只选看作者章节表中的 Prompting patterns，学习如何提供上下文和明确任务。看完改写自己的下一条游戏修改消息。',scope:'对应第 3、5、6 关。原视频主线含 CLI、IDE 和 MCP，本节不用照着安装它们。',verified:'已核对官方频道、简介和章节表；2026-01-12 发布，未逐分钟审看。'},
{id:'quickstart',kind:'article',level:'操作必备',title:'桌面端快速入门',original:'快速入门',publisher:'OpenAI 官方文档',language:'中文（官网自动翻译）',time:'按需查安装、登录和入口',url:'https://learn.chatgpt.com/zh-Hans/docs/quickstart',focus:'只读桌面端设置部分：选择系统、安装登录、选择工作位置和 Codex。页面更新后用它核对按钮入口。',scope:'对应第 2 关。不需要学习 API 或命令行。',verified:'已打开核对正文。'},
{id:'projects',kind:'article',level:'操作必备',title:'项目与本地文件夹',original:'项目和聊天',publisher:'OpenAI 官方文档',language:'中文（官网自动翻译）',time:'先读“使用本地项目处理文件夹和代码库”',url:'https://learn.chatgpt.com/zh-Hans/docs/projects',focus:'搞清“项目名称”和“电脑上的实际文件夹”不是一回事。核对添加文件夹与主文件夹，避免让 AI 改错目录。',scope:'对应第 2、4 关。工作树等进阶内容可先跳过。',verified:'已打开核对本地文件夹部分。'},
{id:'prompting',kind:'article',level:'操作必备',title:'怎样把要求告诉 AI',original:'提示词',publisher:'OpenAI 官方文档',language:'中文（官网自动翻译）',time:'先读“提示词概览”和“为 Codex 编写提示词”',url:'https://learn.chatgpt.com/zh-Hans/docs/prompting',focus:'看目标、上下文、输出、边界怎样帮助表达；再用自己的话写“只把 30 秒改成 45 秒，其他不变”。不用背固定咒语。',scope:'对应第 3、5、6、8 关。先不要扩展到插件和自动化。',verified:'已打开核对正文和 Codex 提示词段落。'},
{id:'agent-reading',kind:'article',level:'概念补充',title:'AI Agent 入门：是什么、能做什么',original:'Introduction to developing AI agents',publisher:'Microsoft Learn',language:'英文；可使用浏览器页面翻译',time:'官方标注 18 分钟 / 6 个单元',url:'https://learn.microsoft.com/en-us/training/modules/introduction-develop-ai-agents/',focus:'先读定义、用途和组成，区分理解需求的模型与执行动作的工具。用自己的矿工项目各举一个例子。',scope:'对应第 1 关。无需先决知识；练习得分/证书可能要求登录，不是本课要求。',verified:'已打开核对模块目标、时长与先决条件。'}]};
window.ARCADE_COURSE.chapters[9].name='课后作业与参考';
window.ARCADE_COURSE.chapters[9].steps.push({name:'课后参考（选看）',visual:'resources',prompt:'homework',action:['先看 2 分钟 Agent 介绍；遇到具体操作问题，再查对应的中文官方文章。','先完成一次自己的游戏练习，再按需看长视频；不要用看完视频代替动手作业。'],expected:'你能解释 Agent 在哪一步读写文件、自己在哪一步试玩，并提交第一版、修改版和真实记录。',help:'外部视频和文章需要联网，部分平台可能要求登录或因网络不可达。无法打开不影响本课离线步骤、手册和预制 Demo。',tip:'课后参考不增加 60 分钟正课时长。外部视频未下载，字幕与界面版本以来源页面为准。'});
